# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app-with-argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lion-app-with-argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lion-app-with-argocd-web
    spec:
      containers:
        - name: nginx
          image: 913524935501.dkr.ecr.ap-northeast-2.amazonaws.com/eks-second:f473c0f6e302e22963d3ab9466518bda67c4003b
