# argocd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lion-app-with-argocd-service
spec:
  selector:
    app.kubernetes.io/name: lion-app-with-argocd-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
