# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app-with-argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lion-app-with-argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lion-app-with-argocd-web
    spec:
      containers:
        - name: nginx
          image: lion-app-with-argocd
