# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app-with-argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lion-app-with-argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lion-app-with-argocd-web
    spec:
      containers:
        - name: nginx
          image: 913524935501.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:cfdd314b5800f85540ec51cab6b3c75456e3bd28
