# argocd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app-with-argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: lion-app-with-argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lion-app-with-argocd-web
    spec:
      containers:
        - name: nginx
          image: dogeun/lion-app-with-actions:281f22a78ecf1b7d1be678965ab12b13cdc8a74b